// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvyokmtedkhpxtdcjmom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2eW9rbXRlZGtocHh0ZGNqbW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODUxNDYsImV4cCI6MjA2MDU2MTE0Nn0.TWmkYwKhMisM4sw3BqUOEuSogJ3lT8SmWmPUCdVemos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);